#!/bin/sh
#
## TITLE: Netsel
## DESCRIPTION: A Wifi netselection program using dmenu.

## Var
term="st -e"
## term = The terminal you use.
sd="doas"
## sd = The root thingie eg (sudo & doas).
interface="wlan0"
## interface = The wifi interface you use (check this with the command [ip a]).
wifi1="HomeWIFI"
wifi2="CoffeSHOPWIFI"
wifi3="WorkWIFI"
## Wifi var.

case "$(printf ">>WIFIScan<<\n$wifi1\n$wifi2\n$wifi3\n>>killwpa<<" | dmenu -l 20 -i)" in
## Format is this [NETWORKNAME\nOTHERNETWORKNAME] ([\n] is for new line. and at the end don't use [\n] because it doesn't need a new line.)
	'>>WIFIScan<<') $term $sd wavemon ;;
	## This scans for wifi connections. [wavemon] is a application that makes it possible to scan for wifi connections in a ncurses tui, to check for wifi connection press [f5].
	$wifi1) $term $sd rfkill unblock all && $term $sd wpa_supplicant -B -i $interface -c ~/.config/netsel/wpaconfig/$wifi1.conf && $term $sd dhcpcd $interface ;;
	## The NEWORKNAME is set here and you should make a conf file in [~/.config/netsel/wpaconfig/NETWORKNAME.conf] and edit the [NETWORKNAME.conf] (a skel file is in (~/.config/netsel/skel/WIFISkel.conf) )
	$wifi2) $term $sd rfkill unblock all && $term $sd wpa_supplicant -B -i $interface -c ~/.config/netsel/wpaconfig/$wifi2.conf && $term $sd dhcpcd $interface ;;
	$wifi3) $term $sd rfkill unblock all && $term $sd wpa_supplicant -B -i $interface -c ~/.config/netsel/wpaconfig/$wifi3.conf && $term $sd dhcpcd $interface ;;
	## If more than three connections than just copy paste ^ this also add it to the top line. eg: ">>WIFIScan<<\n$wifi1\n$wifi2\n$wifi3\n>$NEWWIFIVAR\n>killwpa<<" (also add more var.)
	'>>killwpa<<') $term $sd killall wpa_supplicant ;;
	## This kills the [wpa_supplicant] to reset configurations, and then you can re run the program to connect to a new wifi.

	*) exit 1 ;;
esac
